# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430c8716a4016cede391481ba5ccbeb11a0a6bc019ff2c6163d24c816847ed32e8894c70a2e627b685120144337548197e3a7a01572ef55f5f7ee31cca0b0966

test:
  secret_key_base: 3d5318bebb1152689862fb575ef76655f7dfa9bf7faca8d4d743ef5cf11bc5bf080b83827dc56e37e9dc228c521bc28afa817f223b951b23f20cdb5e475433d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
